var Country = require('./country');

function countries() {
    return [
        new Country('BR', 'Brasil', 'ground'),
        new Country('VN', 'Venezuela', 'ground'),
        new Country('PR', 'Peru', 'ground'),
        new Country('AR', 'Argentina', 'ground'),
        new Country('MX', 'México', 'ground'),
        new Country('CB', 'Cuba', 'ground'),
        new Country('NY', 'New York', 'ground'),
        new Country('CA', 'Califórnia', 'ground'),
        new Country('LB', 'Labrador', 'ground'),
        new Country('OT', 'Ottawa', 'ground'),
        new Country('VC', 'Vancouver', 'ground'),
        new Country('MC', 'Mackenzie', 'ground'),
        new Country('AL', 'Alaska', 'ground'),
        new Country('GL', 'Groenlândia', 'ground'),
        new Country('IS', 'Islândia', 'ground'),
        new Country('IN', 'Inglaterra', 'ground'),
        new Country('FR', 'França', 'ground'),
        new Country('GE', 'Alemanha', 'ground'),
        new Country('PL', 'Polônia', 'ground'),
        new Country('MW', 'Moscow', 'ground'),
        new Country('SC', 'Suécia', 'ground'),
        new Country('AG', 'Argélia', 'ground'),
        new Country('EG', 'Egito', 'ground'),
        new Country('SD', 'Sudão', 'ground'),
        new Country('CG', 'Congo', 'ground'),
        new Country('AS', 'África do sul', 'ground'),
        new Country('MG', 'Madagascar', 'ground'),
        new Country('OM', 'Oriente médio', 'ground'),
        new Country('ID', 'Índia', 'ground'),
        new Country('VT', 'Vietnam', 'ground'),
        new Country('CN', 'China', 'ground'),
        new Country('MO', 'Mongólia', 'ground'),
        new Country('RL', 'Aral', 'ground'),
        new Country('OK', 'Ornsk', 'ground'),
        new Country('DU', 'Dudinka', 'ground'),
        new Country('TH', 'Tchita', 'ground'),
        new Country('VD', 'Vladvostok', 'ground'),
        new Country('SB', 'Sibéria', 'ground'),
        new Country('JP', 'Japão', 'ground'),
        new Country('SM', 'Sumatra', 'ground'),
        new Country('NG', 'Nova Guinea', 'ground'),
        new Country('AU', 'Austrália', 'ground'),
        new Country('BO', 'Bornea', 'ground'),
        new Country('OP', 'Oceano Pacífico', 'ocean'),
        new Country('OA', 'Oceano Atlântico', 'ocean'),
        new Country('OI', 'Oceano Índico', 'ocean'),
        new Country('OR', 'Oceano Ártico', 'ocean'),
        new Country('ON', 'Oceano Antártico', 'ocean')
    ];
}

module.exports = {countries};